### Operações com matrizes

In [1]:
# imports
import numpy as np

<li>Adição

In [ ]:
A = np.array([[3,5],[-4,8]])
B = np.array([[2,-8],[3,7]])

print('A: ',A)
print('B: ',B)

C = A + B

print('Resultado da operação: ', C)

<li> Multiplicação

In [6]:
A = np.array([[3,6,7],[-5,3,0]])
B = np.array([[7,9,1],[2,-8,4]])

print('A: ',A)
print(A.shape)
print()

print('B: ',B)
print(B.shape)
print()

print('Resultado da operação: ',C)
print(C.shape)
print()

D = np.array([[1,3],[5,6],[8,5]])
print('D: ',D)
print(D.shape)
print()

E = A.dot(D) # Usa-se a função dot()
print('Resultado da operação ', E)
print(E.shape)



A:  [[ 3  6  7]
 [-5  3  0]]
(2, 3)

B:  [[ 7  9  1]
 [ 2 -8  4]]
(2, 3)

Resultado da operação:  [[ 21  54   7]
 [-10 -24   0]]
(2, 3)

D:  [[1 3]
 [5 6]
 [8 5]]
(3, 2)

Resultado da operação  [[89 80]
 [10  3]]
(2, 2)


<li> Subtração

In [ ]:
A = np.array([[2,4],[5,-6]])
B = np.array([[9,-3],[8,1]])

print('A ',A)
print('B ',B)
C = A - B
print('Resultado da operação: ',C)

<li> Transposição -> Inversão de dimensões

In [ ]:
A = np.array([[2,7],[5,2],[3,8]])

print('Shape de A ',A.shape)

B = A.transpose()
print('Shape de B ',B.shape)