### Acessando colunas e linhas de uma matriz

In [2]:
# import
import numpy as np

In [3]:
A = np.array([[1,4,5,12],[8,6,9,7],[45,85,5,3]])
print(A)
print()

print('A[:,0]: ',A[:,0]) # Primeira coluna
print('A[:,3]: ',A[:,3]) # Última coluna
print('A[:,-1]: ',A[:,-1]) # Última coluna
print()

# Linhas
print('A[2,:]: ',A[2,:]) # Terceira linha
print('A[1,:]: ',A[1,:]) # Segunda linha
print('A[0,:]: ',A[0,:]) # Primeira linha

# Elementos específicos
print('A[0,1]: ',A[0,1]) # Primeira linha segunda coluna
print('A[2,2]: ',A[2,2]) # Terceira linha terceira coluna
print('A[1,0]: ',A[1,0]) # Segunda linha, primeira coluna

[[ 1  4  5 12]
 [ 8  6  9  7]
 [45 85  5  3]]

A[:,0]:  [ 1  8 45]
A[:,3]:  [12  7  3]
A[:,-1]:  [12  7  3]

A[2,:]:  [45 85  5  3]
A[1,:]:  [8 6 9 7]
A[0,:]:  [ 1  4  5 12]
A[0,1]:  4
A[2,2]:  5
A[1,0]:  8


### Fatiamento de array unidimensional

In [4]:
letters = np.array([1,2,3,4,5,6,7,8])

# Do terceiro ao quinto elemento
print(letters[2:5])

# Do início a sexta posição
print(letters[:6])

# Posição inicial aleatória até o final
print(letters[2:])

# Imprime tudo
print('Imprime tudo')
print(letters)
print(letters[:])

# Inverte os elementos
print(letters[::-1])
print('reversed(letters) ', list(reversed(letters)))
print('reversed(letters) ', tuple(reversed(letters)))



[3 4 5]
[1 2 3 4 5 6]
[3 4 5 6 7 8]
Imprime tudo
[1 2 3 4 5 6 7 8]
[1 2 3 4 5 6 7 8]
[8 7 6 5 4 3 2 1]
reversed(letters)  [8, 7, 6, 5, 4, 3, 2, 1]
reversed(letters)  (8, 7, 6, 5, 4, 3, 2, 1)


### Fatiamento de um array de N dimensões

In [4]:
A = np.array([[8,5,3,7],[1,9,7,-3],[2,-8,7,3]])
print(A.shape)
print(A)

print('A[:2,:4] ',A[:2,:4]) # Duas linhas, quatro colunas
print('A[:,3]',A[:,3]) # Todas as linhas, terceira coluna
print('A[1,:]',A[1,:]) # Primeira linha, todas as colunas
print('A[:,2:5]',A[:,2:5]) # Todas as linhas, duas últimas colunas
print('A[0:2,1:3]',A[0:2,1:3]) # Linha da posição 0 à 2, colunas da posição 1 à 3

(3, 4)
[[ 8  5  3  7]
 [ 1  9  7 -3]
 [ 2 -8  7  3]]
A[:2,:4]  [[ 8  5  3  7]
 [ 1  9  7 -3]]
A[:,3] [ 7 -3  3]
A[1,:] [ 1  9  7 -3]
A[:,2:5] [[ 3  7]
 [ 7 -3]
 [ 7  3]]
A[0:2,1:3] [[5 3]
 [9 7]]
