## Criando Matrizes
### dtype -> tipo da matriz

In [12]:
import numpy as np

lista1 = ['azul','vermelho','roxo'] # Array python

print(lista1)
print(type(lista1))
print()

lista2 = np.array(['azul','vermelho','roxo']) # Em um array numpy, os dados precisam ser do mesmo tipo

print(lista2)
print(type(lista2))
print(lista2.dtype)
print()

lista3 = np.array([1,2,3,4])
print(lista3)
print(lista3.dtype)

['azul', 'vermelho', 'roxo']
<class 'list'>

['azul' 'vermelho' 'roxo']
<class 'numpy.ndarray'>
<U8

[1 2 3 4]
int32


## Array de inteiros
### shape -> dimensão da matriz (linhas por colunas)

In [8]:
import numpy as np

A = np.array([[1,2,3],[3,4,5]]) # Matriz de matrizes
print(A)
print(A.dtype)
print(A.shape)

[[1 2 3]
 [3 4 5]]
int32
(2, 3)


## Array de floats

In [9]:
import numpy as np

A = np.array([[1.5,2,3.7],[3,4,5]])
print(A)
print(A.dtype)
print(A.shape)

[[1.5 2.  3.7]
 [3.  4.  5. ]]
float64
(2, 3)


## Array de números complexos

In [10]:
import numpy as np

A = np.array([[1.5,2,3.7],[3,4,5]],dtype = complex)
print(A)
print(A.dtype)
print(A.shape)

[[1.5+0.j 2. +0.j 3.7+0.j]
 [3. +0.j 4. +0.j 5. +0.j]]
complex128
(2, 3)


### Matriz de zeros e Ums

In [19]:
import numpy as np

matriz_zeros = np.zeros((2,3)) # O shape SEMPRE deve ser passado como uma tupla

print(matriz_zeros)



[[0. 0. 0.]
 [0. 0. 0.]]


In [25]:
import numpy as np

matriz_ones = np.ones((1,5),dtype=np.int32) # O shape SEMPRE deve ser passado como uma tupla. Aqui estamos passando um dtype do numpy, não do python, como foi no exemplo do array de complexos

print(matriz_ones)
print(matriz_ones.dtype)
print()

matriz_ones1 = np.ones((1,5),dtype = int)
print(matriz_ones1)
print(matriz_ones1.dtype)


[[1 1 1 1 1]]
int32

[[1 1 1 1 1]]
int32


### Matriz Vazia

In [30]:
import numpy as np

mn = np.empty((2,3,2)) # As vezes vem lixo, por isso é melhor usar np.zeros. 
                       # Não é um array nulo, e sim, com zeros

print(mn)

mn1 = np.empty((2,3)) # As vezes vem lixo. 
print(mn1)

[[[2.58883487e-312 2.29175545e-312]
  [0.00000000e+000 0.00000000e+000]
  [2.14321575e-312 2.31297541e-312]]

 [[2.29175545e-312 2.35541533e-312]
  [2.35541533e-312 2.35541533e-312]
  [0.00000000e+000 0.00000000e+000]]]
[[0. 0. 0.]
 [0. 0. 0.]]


### arange() e reshape()


In [65]:
# numpy.arange([start, ]stop, [step, ]dtype=None, *, like=None)
# Único obrigatório é o stop

B1 = np.arange(10) # Passando o obrigatório 
print('B1 ',B1)

A = np.arange(start=1, stop=20, step=3)
print('A: ',A)

C = np.arange(6).reshape(2,3) # Em reshape, o produto das dimensões, tem que dar o que foi passado em arange
print(C)

D = B1.reshape(2,5)
print(D)




B1  [0 1 2 3 4 5 6 7 8 9]
A:  [ 1  4  7 10 13 16 19]
[[0 1 2]
 [3 4 5]]
[[0 1 2 3 4]
 [5 6 7 8 9]]


### Acessando colunas e linhas de uma matriz

In [56]:
A = np.array([[1,4,5,12],[8,6,9,7],[45,85,5,3]])
print(A)
print()

print('A[:,0]: ',A[:,0]) # Primeira coluna
print('A[:,3]: ',A[:,3]) # Última coluna
print('A[:,-1]: ',A[:,-1]) # Última coluna
print()

# Linhas
print('A[2,:]: ',A[2,:]) # Terceira linha
print('A[1,:]: ',A[1,:]) # Segunda linha
print('A[0,:]: ',A[0,:]) # Primeira linha

# Elementos específicos
print('A[0,1]: ',A[0,1]) # Primeira linha segunda coluna
print('A[2,2]: ',A[2,2]) # Terceira linha terceira coluna
print('A[1,0]: ',A[1,0]) # Segunda linha, primeira coluna

[[ 1  4  5 12]
 [ 8  6  9  7]
 [45 85  5  3]]

A[:,0]:  [ 1  8 45]
A[:,3]:  [12  7  3]
A[:,-1]:  [12  7  3]

A[2,:]:  [45 85  5  3]
A[1,:]:  [8 6 9 7]
A[0,:]:  [ 1  4  5 12]
A[0,1]:  4
A[2,2]:  5
A[1,0]:  8


### Fatiamento de array unidimensional

In [60]:
letters = np.array([1,2,3,4,5,6,7,8])

# Do terceiro ao quinto elemento
print(letters[2:5])

# Do início a sexta posição
print(letters[:6])

# Posição inicial aleatória até o final
print(letters[2:])

# Imprime tudo
print('Imprime tudo')
print(letters)
print(letters[:])

# Inverte os elementos
print(letters[::-1])
print('reversed(letters) ', list(reversed(letters)))
print('reversed(letters) ', tuple(reversed(letters)))



[3 4 5]
[1 2 3 4 5 6]
[3 4 5 6 7 8]
Imprime tudo
[1 2 3 4 5 6 7 8]
[1 2 3 4 5 6 7 8]
[8 7 6 5 4 3 2 1]
reversed(letters)  [8, 7, 6, 5, 4, 3, 2, 1]
reversed(letters)  (8, 7, 6, 5, 4, 3, 2, 1)


### Fatiamento de um array de N dimensões


In [64]:
A = np.array([[8,5,3,7],[1,9,7,-3],[2,-8,7,3]])
print(A.shape)
print(A)

print('A[:2,:4] ',A[:2,:4]) # Duas linhas, quatro colunas
print('A[:,3]',A[:,3]) # Todas as linhas, terceira coluna
print('A[1,:]',A[1,:]) # Primeira linha, todas as colunas
print('A[:,2:5]',A[:,2:5]) # Todas as linhas, duas últimas colunas
print('A[0:2,1:3]',A[0:2,1:3]) # Linha da posição 0 à 2, colunas da posição 1 à 3

(3, 4)
[[ 8  5  3  7]
 [ 1  9  7 -3]
 [ 2 -8  7  3]]
A[:2,:4]  [[ 8  5  3  7]
 [ 1  9  7 -3]]
A[:,3] [ 7 -3  3]
A[1,:] [ 1  9  7 -3]
A[:,2:5] [[ 3  7]
 [ 7 -3]
 [ 7  3]]
A[0:2,1:3] [[5 3]
 [9 7]]
