## Criando Matrizes
### dtype -> tipo da matriz

In [12]:
import numpy as np

lista1 = ['azul','vermelho','roxo'] # Array python

print(lista1)
print(type(lista1))
print()

lista2 = np.array(['azul','vermelho','roxo']) # Em um array numpy, os dados precisam ser do mesmo tipo

print(lista2)
print(type(lista2))
print(lista2.dtype)
print()

lista3 = np.array([1,2,3,4])
print(lista3)
print(lista3.dtype)

['azul', 'vermelho', 'roxo']
<class 'list'>

['azul' 'vermelho' 'roxo']
<class 'numpy.ndarray'>
<U8

[1 2 3 4]
int32


## Array de inteiros
### shape -> dimensão da matriz (linhas por colunas)

In [8]:
import numpy as np

A = np.array([[1,2,3],[3,4,5]]) # Matriz de matrizes
print(A)
print(A.dtype)
print(A.shape)

[[1 2 3]
 [3 4 5]]
int32
(2, 3)


## Array de floats

In [9]:
import numpy as np

A = np.array([[1.5,2,3.7],[3,4,5]])
print(A)
print(A.dtype)
print(A.shape)

[[1.5 2.  3.7]
 [3.  4.  5. ]]
float64
(2, 3)


## Array de números complexos

In [10]:
import numpy as np

A = np.array([[1.5,2,3.7],[3,4,5]],dtype = complex)
print(A)
print(A.dtype)
print(A.shape)

[[1.5+0.j 2. +0.j 3.7+0.j]
 [3. +0.j 4. +0.j 5. +0.j]]
complex128
(2, 3)


### Matriz de zeros e Ums

In [19]:
import numpy as np

matriz_zeros = np.zeros((2,3)) # O shape SEMPRE deve ser passado como uma tupla

print(matriz_zeros)



[[0. 0. 0.]
 [0. 0. 0.]]


In [25]:
import numpy as np

matriz_ones = np.ones((1,5),dtype=np.int32) # O shape SEMPRE deve ser passado como uma tupla. Aqui estamos passando um dtype do numpy, não do python, como foi no exemplo do array de complexos

print(matriz_ones)
print(matriz_ones.dtype)
print()

matriz_ones1 = np.ones((1,5),dtype = int)
print(matriz_ones1)
print(matriz_ones1.dtype)


[[1 1 1 1 1]]
int32

[[1 1 1 1 1]]
int32


### Matriz Vazia

In [2]:
import numpy as np

mn = np.empty((2,3,2)) # As vezes vem lixo, por isso é melhor usar np.zeros. 
                       # Não é um array nulo, e sim, com zeros

print(mn)

mn1 = np.empty((2,3)) # As vezes vem lixo. 
print(mn1)

[[[6.23042070e-307 4.67296746e-307]
  [1.69121096e-306 1.78020848e-306]
  [7.56587585e-307 1.37961302e-306]]

 [[1.05699242e-307 8.01097889e-307]
  [1.78020169e-306 7.56601165e-307]
  [1.02359984e-306 1.29060531e-306]]]
[[0. 0. 0.]
 [0. 0. 0.]]


### arange() e reshape()
arange() -> Return evenly spaced values within a given interval.

Values are generated within the half-open interval [start, stop) (in other words, the interval including start but excluding stop). For integer arguments the function is equivalent to the Python built-in range function, but returns an ndarray rather than a list.

### Parameters
### startinteger or real, optional
Start of interval. The interval includes this value. The default start value is 0.

### stopinteger or real
End of interval. The interval does not include this value, except in some cases where step is not an integer and floating point round-off affects the length of out.

### stepinteger or real, optional
Spacing between values. For any output out, this is the distance between two adjacent values, out[i+1] - out[i]. The default step size is 1. If step is specified as a position argument, start must also be given.

In [4]:
# numpy.arange([start, ]stop, [step, ]dtype=None, *, like=None)
# Único obrigatório é o stop

B1 = np.arange(10) # Passando o obrigatório 
print('B1 ',B1)

A = np.arange(start=1, stop=20, step=3)
print('A: ',A)

B1  [0 1 2 3 4 5 6 7 8 9]
A:  [ 1  4  7 10 13 16 19]


### reshape(linha,coluna)
Gives a new shape to an array without changing its data.

In [5]:
C = np.arange(6).reshape(2,3) # Em reshape, o produto das dimensões, tem que dar o que foi passado em arange
print(C)

D = B1.reshape(2,5)
print(D)

[[0 1 2]
 [3 4 5]]
[[0 1 2 3 4]
 [5 6 7 8 9]]
