## Criando Matrizes
### dtype -> tipo da matriz

In [12]:
import numpy as np

lista1 = ['azul','vermelho','roxo'] # Array python

print(lista1)
print(type(lista1))
print()

lista2 = np.array(['azul','vermelho','roxo']) # Em um array numpy, os dados precisam ser do mesmo tipo

print(lista2)
print(type(lista2))
print(lista2.dtype)
print()

lista3 = np.array([1,2,3,4])
print(lista3)
print(lista3.dtype)

['azul', 'vermelho', 'roxo']
<class 'list'>

['azul' 'vermelho' 'roxo']
<class 'numpy.ndarray'>
<U8

[1 2 3 4]
int32


## Array de inteiros
### shape -> dimensão da matriz (linhas por colunas)

In [8]:
import numpy as np

A = np.array([[1,2,3],[3,4,5]])
print(A)
print(A.dtype)
print(A.shape)

[[1 2 3]
 [3 4 5]]
int32
(2, 3)


## Array de floats

In [9]:
import numpy as np

A = np.array([[1.5,2,3.7],[3,4,5]])
print(A)
print(A.dtype)
print(A.shape)

[[1.5 2.  3.7]
 [3.  4.  5. ]]
float64
(2, 3)


## Array de números complexos

In [10]:
import numpy as np

A = np.array([[1.5,2,3.7],[3,4,5]],dtype = complex)
print(A)
print(A.dtype)
print(A.shape)

[[1.5+0.j 2. +0.j 3.7+0.j]
 [3. +0.j 4. +0.j 5. +0.j]]
complex128
(2, 3)


### Matriz de zeros e Ums

In [19]:
import numpy as np

matriz_zeros = np.zeros((2,3)) # O shape SEMPRE deve ser passado como uma tupla

print(matriz_zeros)



[[0. 0. 0.]
 [0. 0. 0.]]


In [25]:
import numpy as np

matriz_ones = np.ones((1,5),dtype=np.int32) # O shape SEMPRE deve ser passado como uma tupla. Aqui estamos passando um dtype do numpy, não do python, como foi no exemplo do array de complexos

print(matriz_ones)
print(matriz_ones.dtype)
print()

matriz_ones1 = np.ones((1,5),dtype = int)
print(matriz_ones1)
print(matriz_ones1.dtype)


[[1 1 1 1 1]]
int32

[[1 1 1 1 1]]
int32


### Matriz Vazia

In [30]:
import numpy as np

mn = np.empty((2,3,2)) # As vezes vem lixo, por isso é melhor usar np.zeros. 
                       # Não é um array nulo, e sim, com zeros

print(mn)

mn1 = np.empty((2,3)) # As vezes vem lixo. 
print(mn1)

[[[2.58883487e-312 2.29175545e-312]
  [0.00000000e+000 0.00000000e+000]
  [2.14321575e-312 2.31297541e-312]]

 [[2.29175545e-312 2.35541533e-312]
  [2.35541533e-312 2.35541533e-312]
  [0.00000000e+000 0.00000000e+000]]]
[[0. 0. 0.]
 [0. 0. 0.]]


### arange() e reshape()


In [34]:
# numpy.arange([start, ]stop, [step, ]dtype=None, *, like=None)
# Único obrigatório é o stop

A = np.arange(start=1, stop=20, step=3)
print('A: ',A)

B1 = np.arange(10)
print('B1 ',B1)

C = np.arange(6).reshape(2,3) # O produto tem que dar o que foi passado em arange
print(C)

D = B1.reshape(2,5)
print(D)




A:  [ 1  4  7 10 13 16 19]
B1  [0 1 2 3 4 5 6 7 8 9]
[[0 1 2]
 [3 4 5]]
[[0 1 2 3 4]
 [5 6 7 8 9]]


### Operações com matrizes

<li>Adição

In [37]:
A = np.array([[3,5],[-4,8]])
B = np.array([[2,-8],[3,7]])

print('A: ',A)
print('B: ',B)

C = A + B

print('Resultado da operação: ', C)



A:  [[ 3  5]
 [-4  8]]
B:  [[ 2 -8]
 [ 3  7]]
Resultado:  [[ 5 -3]
 [-1 15]]


<li> Multiplicação

In [44]:
A = np.array([[3,6,7],[-5,3,0]])
B = np.array([[7,9,1],[2,-8,4]])

print('A: ',A)
print(A.shape)
print()

print('B: ',B)
print(B.shape)
print()

C = A*B

print('Resultado da operação: ',C)
print(C.shape)
print()

D = np.array([[1,3],[5,6],[8,5]])
print('D: ',D)
print(D.shape)
print()
E = A.dot(D)
print('Resultado da operação ', E)
print(E.shape)


A:  [[ 3  6  7]
 [-5  3  0]]
(2, 3)

B:  [[ 7  9  1]
 [ 2 -8  4]]
(2, 3)

Resultado:  [[ 21  54   7]
 [-10 -24   0]]
(2, 3)

D:  [[1 3]
 [5 6]
 [8 5]]
(3, 2)

Resultado E  [[89 80]
 [10  3]]
(2, 2)


<li> Subtração

In [45]:
A = np.array([[2,4],[5,-6]])
B = np.array([[9,-3],[8,1]])

print('A ',A)
print('B ',B)
C = A - B
print('Resultado da operação: ',C)

A  [[ 2  4]
 [ 5 -6]]
B  [[ 9 -3]
 [ 8  1]]
Resultado:  [[-7  7]
 [-3 -7]]


<li> Transposição

In [48]:
A = np.array([[2,7],[5,2],[3,8]])

print('Shape de A ',A.shape)

B = A.transpose()
print('Shape de B ',B.shape)


Shape de A  (3, 2)
Shape de B (2, 3)
