Exercício 1: Crie uma matriz de inteiros 4X2 e imprima seus atributos

In [2]:
import numpy

In [9]:
array = numpy.ones([4,2], dtype = numpy.uint16) 
print('array = ',array)
print()
print("Atributos:")
print("1> Shape: ", array.shape)
print("1> DType: ", array.dtype)

array =  [[1 1]
 [1 1]
 [1 1]
 [1 1]]

Atributos:
1> Shape:  (4, 2)
1> DType:  uint16


Exercício 2: Crie uma matriz de inteiros 5X2 de uma faixa entre 100 e 200 de forma que a diferença entre cada elemento seja de 10

In [12]:
array = numpy.arange(100, 200, 10)
array = array.reshape(5,2)
print (array)

[[100 110]
 [120 130]
 [140 150]
 [160 170]
 [180 190]]


Exercício 3: Crie uma matriz de resultados adicionando duas matrizes NumPy.

In [17]:
array1 = numpy.array([[5, 6, 9], [21 ,18, 27]])
array2 = numpy.array([[15 ,33, 24], [4 ,7, 1]])
print('array1',array1)
print('array1.shape',array1.shape)
print()
print('array2',array2)
print('array1.shape',array1.shape)
print()
resultArray  = array1 + array2
print("array1 + array2")
print(resultArray)

array1 [[ 5  6  9]
 [21 18 27]]
array1.shape (2, 3)

array2 [[15 33 24]
 [ 4  7  1]]
array1.shape (2, 3)

array1 + array2
[[20 39 33]
 [25 25 28]]


Exercício 4: Divida a matriz em quatro sub arrays de tamanho igual

In [20]:
print("Matriz 8X3")
sampleArray = numpy.arange(10, 34, 1)
sampleArray = sampleArray.reshape(8,3)
print (sampleArray)

print("\n Dividindo em 4")
subArrays = numpy.split(sampleArray, 4) 
print(subArrays)

Matriz 8X3
[[10 11 12]
 [13 14 15]
 [16 17 18]
 [19 20 21]
 [22 23 24]
 [25 26 27]
 [28 29 30]
 [31 32 33]]

 Dividindo em 4
[array([[10, 11, 12],
       [13, 14, 15]]), array([[16, 17, 18],
       [19, 20, 21]]), array([[22, 23, 24],
       [25, 26, 27]]), array([[28, 29, 30],
       [31, 32, 33]])]


Exercício 5: Crie uma matriz numpy de 3×3 de todos os True's

In [22]:
numpy.ones((3,3), dtype=bool)

array([[ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]])

Exercício 6: Extrair todos os números ímpares de arr

In [3]:
arr = numpy.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

arr[arr % 2 == 1]

array([1, 3, 5, 7, 9])

Exercicio 7: Substitua todos os números ímpares em arr por -1

In [26]:
arr = numpy.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
arr[arr % 2 == 1] = -1
arr

array([ 0, -1,  2, -1,  4, -1,  6, -1,  8, -1])

Exercício 8: Converta uma matriz 1D em uma matriz 2D com 2 linhas

In [30]:
arr = numpy.arange(10)
print('arr',arr)
print('arr.shape',arr.shape)
arr.reshape(2, -1)

arr [0 1 2 3 4 5 6 7 8 9]
arr.shape (10,)


array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])